name: Prettier

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: read

jobs:
  format:
    name: Format Code
    uses: use-nyte/.github/.github/workflows/format-prettier.yml@main
    secrets: inherit
